name: 🐞 Bug report
description: Report a bug to help us improve Scribe-iOS.
labels: "bug"
body:
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched all open issues.
          required: true
  - type: textarea
    attributes:
      label: Behavior
      placeholder: |
        A concise description of what you're experiencing and what you expected to happen.
    validations:
      required: true
      body:
  - type: dropdown
    id: device
    attributes:
      label: Device type
      options:
        - iPhone
        - iPad
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: iOS version
      placeholder: "iOS/iPadOS vX.Y.Z"
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
