name: 🗃️ Data and Wikidata
description: Help Scribe bring free language data to your fingertips.
labels: Data and Wikidata
body:
  - type: input
    id: language
    attributes:
      label: Language
      placeholder: List the related languages if applicable.
    validations:
      required: true
  - type: input
    id: word_type
    attributes:
      label: Word type
      placeholder: Nouns, verbs, translations, adjectives, prepositions, etc.
  - type: dropdown
    id: browsers
    attributes:
      label: Data procedure
      multiple: true
      options:
        - ETL (Wikidata to Scribe)
        - ELT (Add to Wikidata)
        - ETL and ELT
  - type: textarea
    id: choice
    attributes:
      label: Issue
      placeholder: Let us know what your idea is!
    validations:
      required: true
  - type: markdown
    id: note_on_search
    attributes:
      value: |
        ### - You can search Wikidata for language data by putting L: at the start of a [search](https://www.wikidata.org/w/index.php?search=&search=&title=Special%3ASearch&go=Go)
  - type: markdown
    attributes:
      value: |
        Thank you for supporting Scribe and [Wikidata](https://www.wikidata.org/) to create free information platforms!
