name: 🌐 New keyboard 
description: Help Scribe adding keyboard.
labels: "-new keyboard-"
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: I have searched [open issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue)
          required: true
        - label: I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
  - type: textarea
    id: support
    attributes:
      label: Describe what kind of support is needed ?
      placeholder: Explain the language a bit including why support is needed for certain word types, and tell us how Scribe can help people type in it.
    validations:
      required: true
  - type: input
    id: data
    attributes:
      label: Data
      placeholder: What Current amounts of data is present on Wikidata ?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
       Thanks for sharing your interest in bringing another language to Scribe!
